### ISSUE TITLE
Usage of `ResolveIdentifiers`

### ISSUE THREAD

**Issue by Lootwig** [alexeyinkin/dart-macro-util#1]
Very helpful repo - could you add an example for how to use the `ResolveIdentifiers` annotation, though? When I try to annotate any class with it, nothing happens (also no error when annotating something that's _not_ a class).

When cloning the repo and using the annotation on a basic class with e.g.  a `final x = 5;`, the macro throws.

**Comment by alexeyinkin** [comment]
You can find an example here: https://github.com/alexeyinkin/dart-model-fetch/blob/main/model_fetch_firestore/lib/src/macros/firestore_model/firestore_model.dart

This macro can only be used on classes where all fields are `Identifier`s.

**Comment by Lootwig** [comment]
hmm, with that project it's the same with the macro not executing at all. Obviously not an issue since I'm currently not using it - but I still wonder why? I can run other macros (like the official JsonCodable) just fine

**Comment by alexeyinkin** [comment]
You can try cutting down your copy to a bare minimal macro and see what fails for you. Then you can file a bug with Dart with the minimal reproducible example.

**Comment by alexeyinkin** [comment]
In all cases, be sure to include the locally checked-out code with `dependency_overrides` because macros don't run from pub dependencies, it's a known bug:
- https://github.com/dart-lang/sdk/issues/55670

**Comment by Lootwig** [comment]
Ok I didn't realize at first but the checked out project needs to literally be _next to the importing project's_ directory..? The `dependency_overrides` in your project seem to point to directories only next to the _project folder_, do you have a parent one for all these projects with a pubspec.yaml to resolve this issue?

**Comment by alexeyinkin** [comment]
> do you have a parent one for all these projects with a pubspec.yaml to resolve this issue?

No. Not sure why it works for me though since the issue reads more strict than my setting. You can try putting it even closer to avoid going up with `..`
